# This is the configuration used to check the rubocop source code.
# For list of cops 'https://github.com/bbatsov/rubocop/tree/master/config'


AllCops:
  Exclude:
    - 'config/**/*'
    - 'app/main/config/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/node-sass/src/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false
